### ISSUE TITLE
Add SampleRates

### ISSUE THREAD

**Issue by Sawa121212** [Esticonv/Wisp.Comtrade#3]
I want to output to a file using the SaveToFile method. How can I add SampleRates? Because "sampleRate.samplingFrequency" is zero.
![image](https://user-images.githubusercontent.com/36691142/185335975-895d8fe2-419f-4f45-b535-2e21447f3b6b.png)

**Comment by Esticonv** [comment]
Now no ways for control sampleRates. RecordWriter create only one SampleRate with samplingFrequency=0. So record is timestamp guided, which provided in [RecordWriter.AddSample](https://github.com/Esticonv/Wisp.Comtrade/blob/master/Comtrade/RecordWriter.cs#L77)
If you suggest use cases for you request, i will see what can be done
